configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore WebAPI.OutputCache.Redis.sln

build:
  project: WebAPI.OutputCache.Redis.sln       
  verbosity: minimal

after_build:
  - cmd: nuget pack %APPVEYOR_BUILD_FOLDER%\WebAPI.OutputCache.Redis\WebAPI.OutputCache.Redis.nuspec -version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: WebAPI.OutputCache.Redis\WebAPI.OutputCache.Redis.nupkg
    name: WebAPI.OutputCache.Redis

test: off

deploy:
  - provider: Environment
    name: Etch-MyGet
    on:
      branch: master