configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore WebAPI.OutputCache.Redis.sln

build:
  project: WebAPI.OutputCache.Redis.sln       
  verbosity: minimal

test: off

deploy:
  - provider: Environment
    name: Etch-MyGet
    on:
      branch: master